matrix:
  fast_finish: true
  include:
    - python: "3.5.3"
      env: TOXENV=lint
    - python: "3.5.3"
      env: TOXENV=pylint
    - python: "3.5.3"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r requirements.txt
  - pip install pytest
language: python
script: pytest

