TOKEN_FILE = '.token'
USERS_FILE = 'data/users.csv'
NOTES_FILE = 'notes.txt'
GH_NO_EMAIL_SUFFIX = '@users.noreply.github.com'
LABEL_CHERRY_PICKED = 'cherry-picked'
GITHUB_ORGANIZATION_NAME = 'home-assistant'